#include <iostream>
using namespace std;
int main()
{
       cout << "      Student code : 6406021420140" << endl;
       cout << "      Student name : Apiwat Chumnanchaisri" << endl;
       cout << "          Division : Information Tecnology" << endl;
       cout << "              Year : 1" << endl;
       cout << "              Room : ITI_1RA" << endl;
       cout << "               Sex : Male" << endl;
       cout << "               Age : 20 Year old" << endl;
       cout << "          I'm form : Knchanaburi" << endl;
       cout << "       My birthday : 14 January 2001" << endl;
       cout << "   I want to visit : Japan and United State of America" << endl;
       return (0);
}